<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

# **Artificial Intelligence - MSc**
ET5003 - MACHINE LEARNING APPLICATIONS 

### Instructor: Enrique Naredo
### ET5003_Lab-0.8
### Student Name: Xiaoming Zhang
### Student No.: 20158327

# Numpy


This part focuses on Numpy, see <a href="https://numpy.org/doc/stable/user/quickstart.html">numpy quickstart tutorial</a>, which I encourage you to reference throughout the course.


Some problems about numpy



# Problem 11
Normalize a 5x5 random matrix

Solution:
>Z = np.random.random((5,5))
>
>Z = (Z - np.mean (Z)) / (np.std (Z))
>
>print(Z)


In [1]:
import numpy as np
Z = np.random.random((5,5))

Z = (Z - np.mean (Z)) / (np.std (Z))

print(Z)

[[ 1.40871629 -0.12437735  0.91342743  1.11555349 -0.94875499]
 [-1.10398405  0.05753556 -1.60210147 -0.86025701  1.4294224 ]
 [ 0.28284669 -1.389901    0.18634748 -0.66610431  0.98861723]
 [-0.94829087 -0.02552749 -1.56070814  0.5878953   1.28655769]
 [ 0.57687701 -0.76006726  1.64296302 -0.92030822  0.43362257]]


# Problem 12

Multiply a 5x3 matrix by a 3x2 matrix (matrix product)

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10,11,12],
              [13,14,15]
     ])

B = np.array([[1, 2],
              [3, 4],
              [5, 6]
             ])

print(A.dot(B))

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


# Problem 13
Given a 1D array, negate in place all elements which are between 3 and 8.

In [3]:
A = np.arange(10)
print(A)
A[2:8] = A[2:8] * (-1)
print(A)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1 -2 -3 -4 -5 -6 -7  8  9]


# Problem 14
How to find common values between two arrays?


In [4]:
def find_commond(A, B):
    common_list = []
    for i in range(len(A)):
        for j in range(len(B)):
            if A[i] == B[j]:
                common_list.append(A[i])
    return common_list

A = np.arange(10)
B = np.array([2,3,4,11,12])
print(f'A: \n{A}')
print(f'B: \n{B}')
print(f'Common values: \n {find_commond(A, B)}')

A: 
[0 1 2 3 4 5 6 7 8 9]
B: 
[ 2  3  4 11 12]
Common values: 
 [2, 3, 4]


# Problem 15
How to find the most frequent value in an array? (Use `Z = np.random.randint(0,10,50)` to generate the array)

In [6]:
x = np.array([1,2,3,4,5,5,5,6,7,8,8,8,8,9,9])
print("Original array:")
print(x)
  
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 5 5 6 7 8 8 8 8 9 9]
Most frequent value in the above array:
8


### End