<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

# **Artificial Intelligence - MSc**
ET5003 - MACHINE LEARNING APPLICATIONS 

### Instructor: Enrique Naredo
### ET5003_Lab-0.6
### Student Name: Xiaoming Zhang
### Student No.: 20158327

# Numpy


This part focuses on Numpy, see <a href="https://numpy.org/doc/stable/user/quickstart.html">numpy quickstart tutorial</a>, which I encourage you to reference throughout the course.


Some problems about numpy



# Problem 1 

Create a null vector of size 10 (that is a vector that includes 10 zeros) and print it

In [1]:
#solution
import numpy as np
Z = np.zeros(10)

In [2]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Problem 2
Create a null vector of size 10 but the fifth value which is 1 

In [3]:
Z = np.zeros(10)
Z[4] = 1

In [4]:
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# Problem 3
Create a vector with all integer values ranging from 10 to 49 

In [5]:
Z = np.arange(50)[10:]

In [6]:
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Problem 4
 Create a 3x3 matrix with values ranging from 0 to 8 

In [7]:
Z = np.arange(9).reshape(3, 3)

In [8]:
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Problem 5
Create a 3x3x3 array with random values (you can use ` np.random.random`)

In [9]:
Z = np.random.rand(3,3,3)

In [10]:
Z

array([[[0.51348717, 0.46663893, 0.02306226],
        [0.23326278, 0.95885632, 0.80522995],
        [0.06985733, 0.78460431, 0.7058476 ]],

       [[0.34562429, 0.11269604, 0.15917283],
        [0.09911735, 0.53433025, 0.91858616],
        [0.14750183, 0.72593092, 0.22857886]],

       [[0.95509179, 0.06688922, 0.59019858],
        [0.29038931, 0.54060501, 0.90862484],
        [0.91321621, 0.3011854 , 0.40656869]]])

### End